apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: helseopplysninger-pdfgen-alerts
  labels:
    team: helseopplysninger
    app: hopdfgen
  namespace: helseopplysninger
spec:
  alerts:
    - action: Se `kubectl describe pod \{{ $labels.kubernetes_pod_name }}` for events, og `kubectl logs \{{ $labels.kubernetes_pod_name }}` for logger
      alert: {{app}}-fails
      description: '\{{ $labels.app }} er nede i \{{ $labels.kubernetes_namespace }}'
      expr: up{app=~"{{app}}",job="kubernetes-pods"} == 0
      for: 2m
      severity: danger
      sla: respond within 1h, during office hours
  receivers:
    slack:
      channel: '#team-helseopplysninger-feed'